// <auto-generated />
using System;
using CoordinatorTaskProject.Models.CoordinatorDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoordinatorTaskProject.Migrations
{
    [DbContext(typeof(CoordinatorContext))]
    [Migration("20190801191206_updateTable")]
    partial class updateTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoordinatorTaskProject.Models.CoordinatorDb.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileBy");

                    b.Property<DateTime>("FileTime");

                    b.Property<int>("TaskId");

                    b.HasKey("Id");

                    b.ToTable("History");
                });

            modelBuilder.Entity("CoordinatorTaskProject.Models.CoordinatorDb.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<int?>("UpdateId");

                    b.HasKey("TaskId");

                    b.HasIndex("UpdateId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CoordinatorTaskProject.Models.CoordinatorDb.Update", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CurrentRelease");

                    b.Property<string>("NextUpdate");

                    b.Property<int>("SiteId");

                    b.Property<string>("SiteMnemonic");

                    b.Property<int>("UpdateNumber");

                    b.HasKey("Id");

                    b.ToTable("Updates");
                });

            modelBuilder.Entity("CoordinatorTaskProject.Models.CoordinatorDb.Task", b =>
                {
                    b.HasOne("CoordinatorTaskProject.Models.CoordinatorDb.Update", "Update")
                        .WithMany("Tasks")
                        .HasForeignKey("UpdateId");
                });
#pragma warning restore 612, 618
        }
    }
}
